backend = "glx";
vsync = true;

corner-radius = 6.0;

rounded-corners-exclude = [
	"window_type = 'dock'"
];

opacity-rule = ["95:class_g = 'kitty'"];

shadow = true;
shadow-radius = 4;
shadow-opacity = 0.6;
shadow-offset-x = -2;
shadow-offset-y = -2;

wintypes:
{
	dock = { shadow = false; }
};


